version: '3'
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["./runner"]
    restart: "always"
    environment:
      - PORT=3000
